# Generated by Django 4.2.11 on 2024-04-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_question_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.AddField(
            model_name='question',
            name='explanations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(),
        ),
    ]
