# Generated by Django 4.2.11 on 2024-04-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0008_alter_quiz_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="worth",
            field=models.IntegerField(default=1),
        ),
    ]
