# Generated by Django 4.2.11 on 2024-04-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_question_worth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.JSONField(default='old'),
            preserve_default=False,
        ),
    ]
