# Generated by Django 4.2.11 on 2024-04-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='old', max_length=255),
            preserve_default=False,
        ),
    ]
