# Generated by Django 4.2.11 on 2024-04-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_useranalytics_delete_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalytics',
            name='chat_analytics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='quiz_analytics',
            field=models.JSONField(default=dict),
        ),
    ]
