# Generated by Django 4.2.11 on 2024-04-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
